kafka:
  address:
  version: 2.3.0
  mq_cert:
  user_name:
  password:
  algorithm: sha512
  skip_cert_verify: true

postgresql:
  host:
  user:
  port:
  pwd:
  database:
  life: 1000
  max_conn: 500
  max_idle: 250

cassandra:
  host:
  user:
  port:
  pwd:
  keyspace:
