kafka:
  topic: cve_issue_event
  group: message-push-local
push:
  message:
    app_info_key:
    app_info_secret:
    api_address:
    sender:
    template_id:
    signature:
  email:
    smtp_host:
    smtp_password:
    smtp_port:
    smtp_sender:
    smtp_username:
