kafka:
  topic: cve_issue_event
  group: message-push
push:
  message:
    app_info_key:
    app_info_secret:
    api_address:
    sender:
    template_id:
    signature: 开源社区
  email:
    smtp_host: smtp.exmail.qq.com
    smtp_password: bdAg83DZ76cdrq8L
    smtp_port: 465
    smtp_sender: openeuler
    smtp_username: notify@public.openeuler.org
