kafka:
  host: 182.160.6.195:9094
  topic: eur_build_event
  group: message_transfer
  offset: -2
hw_cloud_msg:
  app_info_key: C5I7EH4iPr4xPXRNa65Qg70bATxP
  app_info_secret: slpTMyXRJdAOldFm2bw6fxdtpoQy
  api_address: https://smsapi.cn-south-1.myhuaweicloud.com:443/sms/batchSendSms/v1
  sender: 8824041123653
  template_id: 33fabc75615647a886a87daa7064f766
  signature: 开源社区

