kafka:
  issue:
    topic: gitee_issue_event
    group: message-push-local

  push:
    topic: gitee_push_event
    group: message-push-local

  pr:
    topic: gitee_pr_event
    group: message-push-local

  note:
    topic: gitee_note_event
    group: message-push-local

push:
  message:
    app_info_key:
    app_info_secret:
    api_address:
    sender:
    template_id:
    signature:
  email:
    smtp_host:
    smtp_password:
    smtp_port:
    smtp_sender:
    smtp_username: