name: Check PR Label Owner

on:
  pull_request:
    types:
      - labeled  # 当 PR 被添加标签时触发

permissions:
  pull-requests: write  # 允许修改 PR 标签
  contents: read

jobs:
  check-label-owner:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the label was added by the authorized user
        env:
          GITHUB_TOKEN: ${{ secrets.OWNER_TOKEN }}
          LABEL_NAME: "gate_check_pass"  # 替换为需要检查的标签名称
          AUTHORIZED_USER: "shishupei"  # 替换为被授权添加标签的用户
        run: |
          # 提取仓库信息
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          ISSUE_NUMBER="${{ github.event.pull_request.number }}"
          
          # 获取 PR 的事件历史
          EVENTS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                        -H "Accept: application/vnd.github+json" \
                        "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/events")
          
 
          
          # 筛选 'labeled' 事件并找到与指定标签匹配的记录
          LABEL_ADDER=$(echo "$EVENTS" | jq -r \
            '.[] | select(.event == "labeled" and .label.name == env.LABEL_NAME) | .actor.login' | tail -n 1)
          
          # 如果没有找到标签事件，打印错误并退出
          if [[ -z "$LABEL_ADDER" ]]; then
            echo "No labeled event found for the label '$LABEL_NAME'. Exiting."
            exit 1
          fi
          
          # 检查添加者是否为授权用户
          if [[ "$LABEL_ADDER" != "$AUTHORIZED_USER" ]]; then
            echo "Label '$LABEL_NAME' was added by '$LABEL_ADDER', not '$AUTHORIZED_USER'. Removing it."
          
            # 删除标签
            curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github+json" \
                              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/labels/$LABEL_NAME"
          else
            echo "Label '$LABEL_NAME' was added by the authorized user '$AUTHORIZED_USER'. No action needed."
          fi
