name: Check PR Label Owner

on:
  pull_request:
    types:
      - labeled  # 当 PR 被添加标签时触发

permissions:
  pull-requests: write  # 允许修改 PR 标签
  contents: read

jobs:
  verify-label-owner:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the label was added by the bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_NAME: "gate_check_pass"  # 替换为需要检查的标签名称
          AUTHORIZED_USER: "shishupei"  # 替换为允许添加标签的 bot 用户名
        run: |
          # 提取仓库信息
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          
          # 获取 PR 的事件历史
          EVENTS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                        -H "Accept: application/vnd.github+json" \
                        "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/events")
          
    
          
          # 筛选与指定标签相关的 'labeled' 事件，按时间排序
          LABEL_ADDER=$(echo "$EVENTS" | jq -r \
            --arg LABEL_NAME "$LABEL_NAME" \
            '.[] | select(.event == "labeled" and .label.name == $LABEL_NAME) | .actor.login' | tail -n 1)
          
          # 检查是否有相关事件
          if [[ -z "$LABEL_ADDER" ]]; then
            echo "No labeled event found for the label '$LABEL_NAME'. Exiting."
            exit 0
          fi
          
          # 检查最近的标签操作者是否为授权 bot 用户
          if [[ "$LABEL_ADDER" != "$AUTHORIZED_USER" ]]; then
            echo "Label '$LABEL_NAME' was added by '$LABEL_ADDER', not '$AUTHORIZED_USER'. Removing it."
          
            # 删除标签
            curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github+json" \
                              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/labels/$LABEL_NAME"
          else
            echo "Label '$LABEL_NAME' was added by the authorized bot '$AUTHORIZED_USER'. No action needed."
          fi
