name: Gate Check

on:
  pull_request:
    types: [opened, synchronized, reopened]  # 在PR打开、同步、重新打开时触发

jobs:
  codearts-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Remove Label
        run: |
            # 定义需要移除的标签
            TARGET_LABEL="gate_check_pass"
            
            # 获取当前添加的标签名称
            ADDED_LABEL=${{ github.event.label.name }}
            echo "Added label: $ADDED_LABEL"
            
            # 检查是否为目标标签
            if [[ "$ADDED_LABEL" == "$TARGET_LABEL" ]]; then
              echo "Removing forbidden label: $ADDED_LABEL"
            
              # 调用 GitHub API 删除标签
              curl -X DELETE \
                -H "Authorization: token ${{ secrets.OWNER_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/$TARGET_LABEL
            else
              echo "No action needed for label: $ADDED_LABEL"
            fi
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod +x ./.github/script/codearts_check.sh

      - name: RUN CodeArts Pipeline
        run: ./.github/script/codearts_check.sh $GITHUB_HEAD_REF ${{ github.event.pull_request.number }}  ${{ secrets.CODEARTS_PASSWORD }} ${{ secrets.CODEARTS_PIPELINE }}
