name: PR Event Script Trigger

on:
  pull_request:
    types: [opened, synchronized, reopened]  # 在PR打开、同步、重新打开时触发

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get current branch name
        id: get_param
              - name: Print GitHub context info
        run: |
              echo "PR_Number: ${{ github.event.pull_request.number }}" >> $GITHUB_ENV
              echo "BRANCH_NAME: $GITHUB_BASE_REF" >> $GITHUB_ENV
              echo "CODEARTS_PASSWORD: ${{ secrets.CODEARTS_PASSWORD }}" >> $GITHUB_ENV
              echo "CODEARTS_PIPELINE: ${{ secrets.CODEARTS_PIPELINE }}" >> $GITHUB_ENV
      - name: RUN CodeArts Pipeline
        run: ./codearts_check.sh "$BRANCH_NAME" "$PR_Number"  "$CODEARTS_PASSWORD" "$CODEARTS_PIPELINE"
