name: PR Event Script Trigger

on:
  pull_request:
    types: [opened, synchronized, reopened]  # 在PR打开、同步、重新打开时触发

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"

